language: perl
perl:
  - '5.8.8'
  - '5.12.2'
  - '5.16'
  - '5.20'
  - '5.24'
  - 'dev'
  - 'blead'
matrix:
  include:
    - perl: 5.24
      env: COVERAGE=1
  allow_failures:
    - perl: blead
sudo: false
before_install:
 - eval $(curl https://travis-perl.github.io/init) --auto
